### ISSUE TITLE
[linux]

### ISSUE THREAD

**Issue by NicTanghe** [robmcrosby/BlenderUSDZ#48]
When i try to import a usdz file exported from houdini i get the following error.
```

Warning: 'OBJ_SEQUENCE_properties' doesn't contain '_PT_' with prefix & suffix
Warning: class IMPORT_OT_usdz contains a property which should be an annotation!
/home/tanghe/.config/blender/2.82/scripts/addons/io_scene_usdz/__init__.py:141
    assign as a type annotation: IMPORT_OT_usdz.materials
    assign as a type annotation: IMPORT_OT_usdz.animations
Warning: class EXPORT_OT_usdz contains a property which should be an annotation!
/home/tanghe/.config/blender/2.82/scripts/addons/io_scene_usdz/__init__.py:141
    assign as a type annotation: EXPORT_OT_usdz.exportMaterials
    assign as a type annotation: EXPORT_OT_usdz.exportAnimations
    assign as a type annotation: EXPORT_OT_usdz.bakeTextures
    assign as a type annotation: EXPORT_OT_usdz.bakeAO
    assign as a type annotation: EXPORT_OT_usdz.bakeAOSamples
    assign as a type annotation: EXPORT_OT_usdz.bakeTextureSize
    assign as a type annotation: EXPORT_OT_usdz.globalScale
    assign as a type annotation: EXPORT_OT_usdz.useConverter
0  meshes freed
Warning: property 'release_confirm' not found in keymap item  'OperatorProperties'
Traceback (most recent call last):
  File "/home/tanghe/.config/blender/2.82/scripts/addons/io_scene_usdz/__init__.py", line 54, in execute
    return import_usdz.import_usdz(context, **keywords)
  File "/home/tanghe/.config/blender/2.82/scripts/addons/io_scene_usdz/import_usdz.py", line 19, in import_usdz
    fileName, fileType = fileName.split('.')
ValueError: too many values to unpack (expected 2)
```

**Comment by peta-peta** [comment]
I have the same problem. I created a usdz with iPad2020 "Lidar room scanner" and tried to import the file with blender 2.83 on linux opensuse tumbleweed.
See error:
```
Traceback (most recent call last):
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/__init__.py", line 54, in execute
    return import_usdz.import_usdz(context, **keywords)
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/import_usdz.py", line 34, in import_usdz
    usdData = crate.readUsd()
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/crate_file.py", line 742, in readUsd
    index, jump = self.readUsdItem(data, index)
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/crate_file.py", line 701, in readUsdItem
    index, itemJump = self.readUsdItem(prim, index)
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/crate_file.py", line 701, in readUsdItem
    index, itemJump = self.readUsdItem(prim, index)
  File "/home/peter/.config/blender/2.83/scripts/addons/io_scene_usdz/crate_file.py", line 682, in readUsdItem
    classType = ClassType[metadata.pop('typeName')]
  File "/home/peter/Blender/blender-2.83.2-linux64/2.83/python/lib/python3.7/enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'Camera'

location: <unknown location>:-1


```

**Comment by janispritzkau** [comment]
Same here, but instead I get an error of `struct.error: unpack requires a buffer of 33728 bytes`.

Tested in Blender 2.90.1 on Arch Linux.
