### ISSUE TITLE
Export usdz issue

### ISSUE THREAD

**Issue by Romch** [robmcrosby/BlenderUSDZ#49]
Hi! I'm trying to export a model with your plugin. however, it throws an exception. Could you explain what's going wrong?

Traceback (most recent call last):
  File "/Users/roman/Library/Application Support/Blender/2.82/scripts/addons/io_scene_usdz/__init__.py", line 123, in execute
    return export_usdz.export_usdz(context, **keywords)
  File "/Users/roman/Library/Application Support/Blender/2.82/scripts/addons/io_scene_usdz/export_usdz.py", line 40, in export_usdz
    globalScale = globalScale)
  File "/Users/roman/Library/Application Support/Blender/2.82/scripts/addons/io_scene_usdz/export_usdz.py", line 74, in exportUsdData
    scene.loadContext(context)
  File "/Users/roman/Library/Application Support/Blender/2.82/scripts/addons/io_scene_usdz/scene_data.py", line 830, in loadContext
    bpy.ops.object.mode_set(mode='OBJECT')
  File "/Applications/Blender.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

I used export options:
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = 128
bpy.data.window_managers["WinMan"].(null) = 512

**Comment by jswiderarch** [comment]
Hello,

Were you able to resolve this issue? I'm having same problem. The plugin worked for awhile and stopped working, with this same error.

**Comment by mfargo** [comment]
I'm still having this problem, FWIW.
