### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by samdelara** [robmcrosby/BlenderUSDZ#54]
I'm getting a value error with this on import of a USDZ model. Does this mean the model is too complex?

```
Traceback (most recent call last):
  File "/Users/samdelara/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/__init__.py", line 54, in execute
    return import_usdz.import_usdz(context, **keywords)
  File "/Users/samdelara/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 19, in import_usdz
    fileName, fileType = fileName.split('.')
ValueError: too many values to unpack (expected 2)

location: <unknown location>:-1


```

**Comment by FatSandwich** [comment]
I'm getting that too!
