### ISSUE TITLE
'NoneType' object has no attribute 'value' when importing this model

### ISSUE THREAD

**Issue by ChildishGiant** [robmcrosby/BlenderUSDZ#57]
```
Python: Traceback (most recent call last):
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\__init__.py", line 54, in execute
    return import_usdz.import_usdz(context, **keywords)
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 38, in import_usdz
    importData(context, usdData, tempDir, materials, animations)
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 81, in importData
    materials = importMaterials(usdData, tempDir) if materials else {}
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 435, in importMaterials
    mat = createMaterial(matData, tempDir)
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 454, in createMaterial
    setMaterialInput(data, 'emissiveColor', 'Emission')
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 490, in setMaterialInput
    setShaderInputTexture(data, inputData, inputName)
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 571, in setShaderInputTexture
    texNode = getImageTextureNode(data, inputData.value.parent)
  File "C:\Users\allie\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_scene_usdz\import_usdz.py", line 532, in getImageTextureNode
    filePath = data['tempDir'] + usdTexture['inputs:file'].value
AttributeError: 'NoneType' object has no attribute 'value'

location: <unknown location>:-1
```

Here's the model: https://play.date/static/assets/media/playdate.usdz

**Comment by HoldenFHart** [comment]
The same thing is happening to me as well.   Does anyone have a solution?    I have not textures, colors, my model has fewer than 30K polygons.   Simple models export well.

**Comment by kubus1234** [comment]
Same here. Complex scenes and animations cannot be exported, using blender 2.92.0.
Is there any hope for an update?
