### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by sterlingcrispin** [robmcrosby/BlenderUSDZ#70]
Hey this plugin doesn't seem to work for me,

Blender Version 2.90.1 (2.90.1 2020-09-23)

`Traceback (most recent call last):
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/__init__.py", line 54, in execute
    return import_usdz.import_usdz(context, **keywords)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 38, in import_usdz
    importData(context, usdData, tempDir, materials, animations)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 81, in importData
    materials = importMaterials(usdData, tempDir) if materials else {}
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 435, in importMaterials
    mat = createMaterial(matData, tempDir)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 448, in createMaterial
    setMaterialInput(data, 'diffuseColor', 'Base Color')
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 490, in setMaterialInput
    setShaderInputTexture(data, inputData, inputName)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 571, in setShaderInputTexture
    texNode = getImageTextureNode(data, inputData.value.parent)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 540, in getImageTextureNode
    mapNode = getTextureMappingNode(data, usdTexture)
  File "/Users/sterlingcrispin/Library/Application Support/Blender/2.90/scripts/addons/io_scene_usdz/import_usdz.py", line 514, in getTextureMappingNode
    uvMap = stData['inputs:varname'].value
AttributeError: 'NoneType' object has no attribute 'value'

location: <unknown location>:-1

`

**Comment by SEIZMICdesign** [comment]
were you even able to get the plugin to load? I don't understand where the correct file to load is located.
