### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by innoreq** [robmcrosby/BlenderUSDZ#86]
When exporting an object, this error is thrown - any ideas on how to fix this (or workaround it)?

```
Python: Traceback (most recent call last):
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/__init__.py", line 164, in execute
    return export_usdz.export_usdz(context, **keywords)
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/export_usdz.py", line 32, in export_usdz
    usdData, texturePaths = exportUsdData(context = context,
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/export_usdz.py", line 74, in exportUsdData
    scene.loadContext(context)
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/scene_data.py", line 843, in loadContext
    self.loadObjects()
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/scene_data.py", line 851, in loadObjects
    self.addBpyObject(obj, obj.type)
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/scene_data.py", line 904, in addBpyObject
    obj.setAsMesh()
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/scene_data.py", line 483, in setAsMesh
    self.createMaterials()
  File "...Library/Application Support/Blender/3.2/scripts/addons/io_scene_usdz/scene_data.py", line 458, in createMaterials
    if slot.material.name in self.scene.materials:
AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by sickrusty** [comment]
i have this problem too

**Comment by sickrusty** [comment]
do you find out why? let me know
